// Define the menu items in the correct format expected by the application
const LAYERS_BAKESHOP_MENU = [
  {
    Category: "Cheesecakes",
    "Item Name": "Marble / White Chocolate Cheesecake",
    "Price (Rs.)": 2000,
    Description: "Creamy cheesecake with white chocolate and marble swirls.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Nutella Cheesecake",
    "Price (Rs.)": 2000,
    Description: "Rich cheesecake with Nutella chocolate hazelnut spread.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Oreo Cheesecake",
    "Price (Rs.)": 2000,
    Description: "Classic cheesecake with Oreo cookie pieces.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Lotus Cheesecake",
    "Price (Rs.)": 1800,
    Description: "Cheesecake with caramelized Lotus Biscoff cookies.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Strawberry Cheesecake",
    "Price (Rs.)": 1800,
    Description: "Fresh strawberry topped cheesecake.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Blueberry Cheesecake",
    "Price (Rs.)": 1800,
    Description: "Sweet blueberry topped cheesecake.",
  },
  {
    Category: "Cheesecakes",
    "Item Name": "Mango Cheesecake",
    "Price (Rs.)": 1800,
    Description: "Tropical mango flavored cheesecake.",
  },
  {
    Category: "Brownies",
    "Item Name": "Hershey's Fudge Brownie",
    "Price (Rs.)": 300,
    Description: "A gooey treat for a classic chocolate brownie.",
  },
  {
    Category: "Brownies",
    "Item Name": "Nutella Brownie",
    "Price (Rs.)": 300,
    Description: "Slathered generously on a super moist brownie.",
  },
  {
    Category: "Brownies",
    "Item Name": "Peanut Butter Brownie",
    "Price (Rs.)": 280,
    Description: "Creamy peanut butter swirled into a rich brownie.",
  },
  {
    Category: "Brownies",
    "Item Name": "Lotus Brownie",
    "Price (Rs.)": 280,
    Description: "Topped with caramelized Lotus Biscoff spread.",
  },
  {
    Category: "Brownies",
    "Item Name": "Oreo Brownie",
    "Price (Rs.)": 280,
    Description: "Crunchy Oreo cookies baked into a fudgy brownie.",
  },
  {
    Category: "Brownies",
    "Item Name": "Ferrero Rocher Brownie",
    "Price (Rs.)": 280,
    Description: "Luxury brownie with Ferrero Rocher chocolate.",
  },
  {
    Category: "Brownies",
    "Item Name": "Snickers Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with Snickers candy bar pieces.",
  },
  {
    Category: "Brownies",
    "Item Name": "Twix Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with Twix candy bar pieces.",
  },
  {
    Category: "Brownies",
    "Item Name": "Kitkat Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with Kitkat chocolate wafer pieces.",
  },
  {
    Category: "Brownies",
    "Item Name": "Bounty Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with coconut-filled Bounty chocolate.",
  },
  {
    Category: "Brownies",
    "Item Name": "Mars Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with Mars chocolate bar pieces.",
  },
  {
    Category: "Brownies",
    "Item Name": "Toblerone Brownie",
    "Price (Rs.)": 280,
    Description: "Brownie with Swiss Toblerone chocolate.",
  },
  {
    Category: "Cakes",
    "Item Name": "Chocolate Fudge Cake",
    "Price (Rs.)": 1700,
    Description: "Rich chocolate cake with fudge frosting.",
  },
  {
    Category: "Cakes",
    "Item Name": "Red Velvet Cake",
    "Price (Rs.)": 1800,
    Description: "Classic red velvet cake with cream cheese frosting.",
  },
  {
    Category: "Cakes",
    "Item Name": "Nutella Cake",
    "Price (Rs.)": 1800,
    Description: "Chocolate cake with Nutella hazelnut chocolate frosting.",
  },
  {
    Category: "Cakes",
    "Item Name": "Lotus Cake",
    "Price (Rs.)": 1800,
    Description: "Cake with caramelized Lotus Biscoff cookie frosting.",
  },
  {
    Category: "Cakes",
    "Item Name": "Oreo Cake",
    "Price (Rs.)": 1800,
    Description: "Chocolate cake with Oreo cookie frosting and pieces.",
  },
  {
    Category: "Cakes",
    "Item Name": "Ferrero Rocher Cake",
    "Price (Rs.)": 2000,
    Description: "Luxury cake with Ferrero Rocher chocolate.",
  },
  {
    Category: "Cakes",
    "Item Name": "Kitkat Cake",
    "Price (Rs.)": 2000,
    Description: "Chocolate cake surrounded by Kitkat chocolate wafers.",
  },
  {
    Category: "Sundaes",
    "Item Name": "Red Velvet Sundae",
    "Price (Rs.)": 550,
    Description: "Creamy vanilla ice cream with red velvet cake pieces and cream cheese frosting",
  },
  {
    Category: "Sundaes",
    "Item Name": "3 Milk Sundae",
    "Price (Rs.)": 550,
    Description: "Vanilla ice cream with tres leches cake pieces and caramel drizzle",
  },
  {
    Category: "Sundaes",
    "Item Name": "Nutella Sundae",
    "Price (Rs.)": 550,
    Description: "Chocolate ice cream with Nutella swirls and hazelnut pieces",
  },
  {
    Category: "Sundaes",
    "Item Name": "Galaxy Sundae",
    "Price (Rs.)": 550,
    Description: "Chocolate ice cream with Galaxy chocolate pieces and chocolate sauce",
  },
  {
    Category: "Premium Sundaes",
    "Item Name": "Lotus 3 Milk Sundae",
    "Price (Rs.)": 620,
    Description: "Tres leches cake with Lotus Biscoff spread, vanilla ice cream and Lotus crumbs",
  },
  {
    Category: "Premium Sundaes",
    "Item Name": "Pistachio Tresleches Sundae",
    "Price (Rs.)": 620,
    Description: "Tres leches cake with pistachio cream, vanilla ice cream and crushed pistachios",
  },
  {
    Category: "Cupcakes",
    "Item Name": "Chocolate Cupcake",
    "Price (Rs.)": 200,
    Description: "Classic chocolate cupcake with chocolate frosting.",
  },
  {
    Category: "Cupcakes",
    "Item Name": "Red Velvet Cupcake",
    "Price (Rs.)": 200,
    Description: "Red velvet cupcake with cream cheese frosting.",
  },
  {
    Category: "Cupcakes",
    "Item Name": "Vanilla Cupcake",
    "Price (Rs.)": 200,
    Description: "Light vanilla cupcake with vanilla buttercream.",
  },
  {
    Category: "Cupcakes",
    "Item Name": "Oreo Cupcake",
    "Price (Rs.)": 200,
    Description: "Cupcake with Oreo cookie pieces and frosting.",
  },
  {
    Category: "Cookies",
    "Item Name": "Chocolate Chip Cookie",
    "Price (Rs.)": 380,
    Description: "Classic cookie with chocolate chips.",
  },
  {
    Category: "Cookies",
    "Item Name": "Double Chocolate Cookie",
    "Price (Rs.)": 380,
    Description: "Chocolate cookie with chocolate chips.",
  },
  {
    Category: "Cookies",
    "Item Name": "Nutella Cookie",
    "Price (Rs.)": 380,
    Description: "Cookie with Nutella hazelnut chocolate.",
  },
]

// Export the layersBakeshopData with the correct menu structure
export const layersBakeshopData = {
  id: "layers-bakeshop",
  name: "Layers Bakeshop",
  description: "Delicious cakes, pastries, and desserts for every occasion.",
  logo: "/images/layers-bakeshop-logo.png",
  heroImage: "/placeholder.svg?height=300&width=800",
  rating: 4.8,
  reviews: 342,
  categories: ["Desserts", "Bakery", "Cakes"],
  menu: LAYERS_BAKESHOP_MENU,
}
