// Ranchers menu data
export const RANCHERS_MENU = [
  {
    Category: "Deals",
    "Item Name": "Happiness Squared Deal",
    "Price (Rs.)": 1799,
    Description: "Special combo deal for sharing.",
  },
  {
    Category: "Deals",
    "Item Name": "Any Two Deal",
    "Price (Rs.)": 1499,
    Description: "Choose any two items from selected menu.",
  },
  {
    Category: "Deals",
    "Item Name": "Two For You",
    "Price (Rs.)": 1999,
    Description: "Premium combo deal for two people.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Bronco Chicken Burger",
    "Price (Rs.)": 599,
    Description: "Crispy chicken burger with special bronco sauce.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Cronco Chicken Burger",
    "Price (Rs.)": 599,
    Description: "Crispy chicken burger with cronco sauce and toppings.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Chee Haww Chicken Burger",
    "Price (Rs.)": 899,
    Description: "Signature chicken burger with cheese and special sauce.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Mighty Rodeo Chicken Burger",
    "Price (Rs.)": 899,
    Description: "Large chicken burger with rodeo sauce and toppings.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Big Bang",
    "Price (Rs.)": 899,
    Description: "Extra large chicken burger with special sauce.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Big Ben",
    "Price (Rs.)": 899,
    Description: "Tower chicken burger with multiple layers.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Fajita",
    "Price (Rs.)": 749,
    Description: "Chicken fajita style burger with peppers and onions.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Pablito",
    "Price (Rs.)": 599,
    Description: "Chicken burger with special pablito sauce.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Cowboy",
    "Price (Rs.)": 599,
    Description: "Western-style chicken burger with BBQ sauce.",
  },
  {
    Category: "Chicken Burgers",
    "Item Name": "Krunch",
    "Price (Rs.)": 249,
    Description: "Value chicken burger with crispy coating.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Rancheronii",
    "Price (Rs.)": 799,
    Description: "Beef burger with special ranch sauce.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Chee Haw Beef",
    "Price (Rs.)": 899,
    Description: "Signature beef burger with cheese and special sauce.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Mighty Rodeo Beef",
    "Price (Rs.)": 899,
    Description: "Large beef burger with rodeo sauce and toppings.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Butcher",
    "Price (Rs.)": 799,
    Description: "Premium beef burger with butcher's special sauce.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Texas Jack",
    "Price (Rs.)": 899,
    Description: "Texas-style beef burger with jack cheese.",
  },
  {
    Category: "Beef Burgers",
    "Item Name": "Beef Steak",
    "Price (Rs.)": 749,
    Description: "Steak sandwich with beef and special sauce.",
  },
  {
    Category: "Chicken",
    "Item Name": "Nuggets",
    "Price (Rs.)": 549,
    Description: "Crispy chicken nuggets.",
  },
  {
    Category: "Chicken",
    "Item Name": "Chicken Pieces",
    "Price (Rs.)": 225,
    Description: "Crispy fried chicken pieces.",
  },
  {
    Category: "Chicken",
    "Item Name": "Whackerr",
    "Price (Rs.)": 399,
    Description: "Special crispy chicken strips.",
  },
  {
    Category: "Chicken",
    "Item Name": "Messy Wings",
    "Price (Rs.)": 499,
    Description: "Chicken wings with messy sauce.",
  },
  {
    Category: "Fries",
    "Item Name": "Waffle Fries",
    "Price (Rs.)": 349,
    Description: "Crispy waffle-shaped potato fries.",
  },
  {
    Category: "Fries",
    "Item Name": "Gun Smoked Fries",
    "Price (Rs.)": 699,
    Description: "Fries with smoky seasoning and toppings.",
  },
  {
    Category: "Fries",
    "Item Name": "Curly Fries",
    "Price (Rs.)": 349,
    Description: "Spiral-cut seasoned potato fries.",
  },
  {
    Category: "Fries",
    "Item Name": "Rancheese",
    "Price (Rs.)": 699,
    Description: "Fries topped with ranch sauce and cheese.",
  },
  {
    Category: "Fries",
    "Item Name": "Plain Fries",
    "Price (Rs.)": 199,
    Description: "Classic crispy french fries.",
  },
  {
    Category: "Fries",
    "Item Name": "Chicky Fries",
    "Price (Rs.)": 499,
    Description: "Fries topped with chicken pieces.",
  },
  {
    Category: "Fries",
    "Item Name": "Frizza",
    "Price (Rs.)": 549,
    Description: "Pizza-style loaded fries with toppings and cheese.",
  },
]

export const ranchersData = {
  id: "ranchers",
  name: "Ranchers",
  description: "Premium burgers and ranch-style dishes",
  logo: "/images/ranchers-logo.png",
  heroImage: "/placeholder.svg?height=300&width=800",
  rating: 4.7,
  reviews: 180,
  categories: ["Burgers", "American", "BBQ"],
  menu: RANCHERS_MENU,
}
